// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260709045655_AddMembershipDiscountPercentage")]
    partial class AddMembershipDiscountPercentage
    {
        
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.MembershipPlan", b =>
                {
                    b.Property<string>("MembershipPlanId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("ElectricityCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExpectedMembers")
                        .HasColumnType("int");

                    b.Property<decimal>("GSTPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaintenanceCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaximumBooksAllowed")
                        .HasColumnType("int");

                    b.Property<int>("MaximumReservationsAllowed")
                        .HasColumnType("int");

                    b.Property<decimal>("MembershipDiscountPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MembershipFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MembershipName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MiscellaneousExpenses")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NumberOfBookCopies")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBooks")
                        .HasColumnType("int");

                    b.Property<decimal>("ProfitPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("StaffSalary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MembershipPlanId");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Aadhaar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MembershipPlanId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PaidMembershipFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
